### PR TITLE
Storybook: loads all *.stories.js

### PR DESCRIPTION
**Pull request by MiroslavPetrik**
fix https://github.com/Kamahl19/react-starter/issues/37

### CODE REVIEW

**Comment by Kamahl19** [comment]
i was just going to do this :D

**Comment by MiroslavPetrik** [comment]
@Kamahl19 that's why we should use the assigne field for the issue.

**Comment by Kamahl19** [comment]
yep definitely, i always use it

**Comment by MiroslavPetrik** [comment]
I just wanted to paste your code so in the long term I have more commits & large portion of all contributions

**Comment by Kamahl19** [comment]
:D

**Pull request merged**
