### PR TITLE
Cleanup header

### PR DESCRIPTION
**Pull request by MiroslavPetrik**
fix https://github.com/Kamahl19/react-starter/issues/22

### CODE REVIEW

**Comment by MiroslavPetrik** [comment]
fixes https://github.com/Kamahl19/react-starter/issues/21

**Comment by Kamahl19** [comment]
image

**Comment by Kamahl19** [comment]
image
since we dont have a Container component nor .container class, we should remove it althogether

**Comment by MiroslavPetrik** [comment]
The container is no longer in the project. thats why I didn't fix ,....

**Comment by MiroslavPetrik** [comment]
Same for the Nav - we have Navbar and only the Responsive menu has #fff - it's fixed in the responsinve menu bug

**Pull request merged**
